Wait for all assets before release
mongodb-js/mongosh pull request #306
Opened 2020-09-10 08:09 UTC by mcasimir

A temporary fix to prevent the release to take place if some of the assets where not generated properly.

We retry the verification of download center config until succeeds for 1 hour. If after 1 hour the config would still be missing assets the release will fail.

2020-09-10 08:21 UTC, addaleax approved these changes

2020-09-10 08:21 UTC, addaleax commented on packages/build/src/download-center.ts
> +const delay = (msecs): any => new Promise((resolve) => {
This could be 

```suggestion
const delay = (msecs): Promise<void> => new Promise((resolve) => {
```

, right?

2020-09-10 08:26 UTC, lrlna requested changes
I am not sure this is the right approach, since we can't restart the other build variants from this function and have to look manually as to what was wrong with the build variant that failed. So this just goes in a loop for a whole hour while we manually fix one of the build variants that fails and restart the whole build process anyways. Do you know what I mean?

2020-09-10 08:28 UTC, mcasimir commented on packages/build/src/download-center.ts
> +const delay = (msecs): any => new Promise((resolve) => {
yep!

2020-09-10 08:37 UTC, mcasimir commented
> I am not sure this is the right approach, since we can't restart the other build variants from this function and have to look manually as to what was wrong with the build variant that failed. So this just goes in a loop for a whole hour while we manually fix one of the build variants that fails and restart the whole build process anyways. Do you know what I mean?

Is not the right approach by all means, we discussed that with max already and concluded that we'd rather have to do a whole new release than having a broken one. 

The idea is to fail if something is not right, then to fix that we will have to do another commit / release. I really hope EVG to have a better way.

2020-09-10 09:38 UTC, lrlna commented
@mcasimir so you're using this as a way to run the `release_macos` as the very last task in the build chain?

2020-09-10 09:58 UTC, mcasimir commented
> @mcasimir so you're using this as a way to run the `release_macos` as the very last task in the build chain?

Yep, to don't go on with releasing on the download center and github unless everything was good (all platform tests and build succeded). Is something less than ideal though, but at least we have the safe guard, we can / should improve that if EVG doesn't offer a functionality. However we don't want to risk to have releases done when stuff goes off.

2020-09-10 10:48 UTC, lrlna approved these changes

2020-09-10 18:22 UTC, mcasimir commented
Going to pause on this one and see if we can move this check to evergreen deps instead

2020-09-11 17:10 UTC, mcasimir commented
Closed in favor of https://github.com/mongodb-js/mongosh/pull/311

2020-09-11 17:10 UTC, closed without merging